### ISSUE TITLE
quantiztion and non-idealities factor

### ISSUE THREAD

**Issue by MySHworks** [coreylammie/MemTorch#86]
Hello, I am a college student. I've been using the Memtorch you developed, recently. I have to say that this is a very good simulation library, which implements a lot of functions. It provides great convenience for the research of memristor - based network.
However, I encountered some problems in the process of using it. I hope you can give me some advice.
At First, The accuracy of the model didn't change when I added the non-idealities factor using apply_nonidealities.And the accuracy doesn't change much when you run the example you provided. May I ask what the reason is? In addition, when I was in use memtorch. Bh. Quantize.quantize function to quantify my model, it seems doesn't work.But my code is a one-to-one correspondence to the example.

**Comment by coreylammie** [comment]
Hi @MySHworks,

Thank you for reaching out! Could you please attach your simulation routines or minimal working examples so I can investigate further? The accuracy degradation observed will depend on what non-ideal characteristics you are introducing to your device model/peripheral circuitry, and the exact parameters in which you have used.

If you could provide a specific error message for `memtorch.bh.Quantize.quantize` and more information, it would be appreciated. In addition, could you please specify:

1. The version of MemTorch you are using (CPU/GPU, Operating System, Instillation Source);
2. The Python version that you are using.

These will enable me to better identify any specific issues that you may be encountering.

Kind Regards,

Corey.

**Comment by MySHworks** [comment]
Thank you for your reply! I'm using the GPU version of Memtorch for Linux, installed using pip directly. And the Python version used is 3.6.9.
Here is my code.
`def test(model,
        test_loader,
        batch_size = 16,
        img_size = 416,
        iou_thres = 0.5,
        conf_thres = 0.001,
        nms_thres = 0.5):

        model.eval()
        seen =0
        s = ('%20s' + '%10s' * 6) % ('Class', 'Images', 'Targets', 'P', 'R', 'mAP', 'F1')
        p, r, f1, mp, mr, mAP, mf1 = 0., 0., 0., 0., 0., 0., 0.
        loss = torch.zeros(3)
        jdict, stats, ap, ap_class = [], [], [], []

        for batch_i,(imgs, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
                targets = targets.to(device)
                imgs = imgs.to(device)
                _, channels, height, width = imgs.shape
                #Run model
                inf_out, train_out = model(imgs)

                #Compute loss
                if hasattr(model, 'hyp'):
                        loss += compute_loss(train_out,targets,model)[1][:3].cpu() #GIoU, obj,cls

                #Run NMS
                output = non_max_suppression(inf_out, conf_thres=conf_thres,nms_thres=nms_thres)
                #Statistics per image
                for si, pred in enumerate(output):
                        labels = targets[targets[:,0] == si,1:]
                        nl = len(labels)
                        tcls = labels[:,0].tolist() if nl else [] #target class
                        seen += 1
                        if pred is None:
                                if nl:
                                        stats.append(([], torch.Tensor(), torch.Tensor(), tcls))
                                continue
                        #Clip boxes to image bounds
                        clip_coords(pred, (height, width))
                        #Assign all predictions as incorrect
                        correct = [0] * len(pred)
                        if nl:
                                detected = []
                                tcls_tensor = labels[:,0]
                                #target boxes
                                tbox = xywh2xyxy(labels[:,1:5])
                                tbox[:, [0,2]] *= width
                                tbox[:, [1,3]] *= height

                                #Search for correct predictions
                                for i, (*pbox, pconf, pcls_conf, pcls) in enumerate(pred):

                                        #Break if all targets already located in image
                                        if len(detected) == nl:
                                                break

                                        #Continue if predicted class not among image classes
                                        if pcls.item() not in tcls:
                                                continue

                                        # Best iou, index between pred and targets
                                        m = (pcls == tcls_tensor).nonzero().view(-1)
                                        iou, bi = bbox_iou(pbox, tbox[m]).max(0)

                                        # If iou > threshold and class is correct mark as correct
                                        if iou > iou_thres and m[bi] not in detected:
                                                correct[i] = 1
                                                detected.append(m[bi])

                        # Append statistics (correct, conf, pcls, tcls)
                        stats.append((correct, pred[:, 4].cpu(), pred[:, 6].cpu(), tcls))

        # Compute statistics
        stats = [np.concatenate(x, 0) for x in list(zip(*stats))]  # to numpy
        if len(stats):
                p, r, ap, f1, ap_class = ap_per_class(*stats)
                mp, mr, mAP, mf1 = p.mean(), r.mean(), ap.mean(), f1.mean()
                nt = np.bincount(stats[3].astype(np.int64), minlength=nc)  # number of targets per class
        else:
                nt = torch.zeros(1)

        # Print results
        pf = '%20s' + '%10.3g' * 6  # print format
        print(pf % ('all', seen, nt.sum(), mp, mr, mAP, mf1))

        # Return results
        maps = np.zeros(nc) + mAP
        for i, c in enumerate(ap_class):
                maps[c] = ap[i]

        return (mp, mr, mAP, mf1, *(loss / len(dataloader)).tolist()), maps

reference_memristor = memtorch.bh.memristor.VTEAM
reference_memristor_params = {'time_series_resolution': 1e-10}
memristor = reference_memristor(**reference_memristor_params)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = Darknet(opt.cfg).to(device)
if opt.weights:
        if opt.weights.endswith(".pt"):
                model.load_state_dict(torch.load(opt.weights,map_location=device)['model'])
        else:
                _ = load_darknet_weights(model, opt.weights)

patched_model = patch_model(copy.deepcopy(model),
                          memristor_model=reference_memristor,
                          memristor_model_params=reference_memristor_params,
                          module_parameters_to_patch=[torch.nn.Linear,torch.nn.Conv2d],
                          mapping_routine=naive_map,
                          transistor=True,
                          programming_routine=None,
                          scheme=memtorch.bh.Scheme.DoubleColumn,
                          tile_shape=(128,128),
                          max_input_voltage=0.3,
                          scaling_routine=naive_scale,
                          ADC_resolution=4,
                          ADC_overflow_rate=0.,
                          quant_method='linear')
patched_model.tune_()
data = parse_data_cfg(opt.data)
nc = int(data['classes'])
test_path = data['valid']
dataset = LoadImagesAndLabels(test_path, opt.img_size, opt.batch_size)
dataloader = DataLoader(dataset,
                        batch_size=opt.batch_size,
                        num_workers=min([os.cpu_count(), opt.batch_size, 16]),
                        pin_memory=True,
                        collate_fn=dataset.collate_fn)
patched_model_ = apply_nonidealities(copy.deepcopy(patched_model),
                non_idealities=[memtorch.bh.nonideality.NonIdeality.DeviceFaults],
                lrs_proportion=0.25,
                hrs_proportion=0.10,
                electroform_proportion=0)
patched_model_.tune_()
with torch.no_grad():
        origin_model_metric = test(patched_model,dataloader)
print("mAP:",f'{origin_model_metric[1].mean():.6f}')`

I can run the demo you provided normally with the accuracy degrade. However, in my own code , no matter what non-ideal factors I add, the accuracy of the patched_model doesn't change. This problem has been bothering me for days.  Hope you can give me some advice. 
Thank you very much!

**Comment by MySHworks** [comment]
Thank you for your reply! I'm using the GPU version of Memtorch for Linux, installed using pip directly. And the Python version used is 3.6.9.
Here is my code.

```
def test(model,test_loader,batch_size = 16,img_size = 416, iou_thres = 0.5,conf_thres = 0.001, nms_thres = 0.5):
        model.eval()
        seen =0
        s = ('%20s' + '%10s' * 6) % ('Class', 'Images', 'Targets', 'P', 'R', 'mAP', 'F1')
        p, r, f1, mp, mr, mAP, mf1 = 0., 0., 0., 0., 0., 0., 0.
        loss = torch.zeros(3)
        jdict, stats, ap, ap_class = [], [], [], []

        for batch_i,(imgs, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
                targets = targets.to(device)
                imgs = imgs.to(device)
                _, channels, height, width = imgs.shape
                #Run model
                inf_out, train_out = model(imgs)

                #Compute loss
                if hasattr(model, 'hyp'):
                        loss += compute_loss(train_out,targets,model)[1][:3].cpu() #GIoU, obj,cls

                #Run NMS
                output = non_max_suppression(inf_out, conf_thres=conf_thres,nms_thres=nms_thres)
                #Statistics per image
                for si, pred in enumerate(output):
                        labels = targets[targets[:,0] == si,1:]
                        nl = len(labels)
                        tcls = labels[:,0].tolist() if nl else [] #target class
                        seen += 1
                        if pred is None:
                                if nl:
                                        stats.append(([], torch.Tensor(), torch.Tensor(), tcls))
                                continue
                        #Clip boxes to image bounds
                        clip_coords(pred, (height, width))
                        #Assign all predictions as incorrect
                        correct = [0] * len(pred)
                        if nl:
                                detected = []
                                tcls_tensor = labels[:,0]
                                #target boxes
                                tbox = xywh2xyxy(labels[:,1:5])
                                tbox[:, [0,2]] *= width
                                tbox[:, [1,3]] *= height

                                #Search for correct predictions
                                for i, (*pbox, pconf, pcls_conf, pcls) in enumerate(pred):

                                        #Break if all targets already located in image
                                        if len(detected) == nl:
                                                break

                                        #Continue if predicted class not among image classes
                                        if pcls.item() not in tcls:
                                                continue

                                        # Best iou, index between pred and targets
                                        m = (pcls == tcls_tensor).nonzero().view(-1)
                                        iou, bi = bbox_iou(pbox, tbox[m]).max(0)

                                        # If iou > threshold and class is correct mark as correct
                                        if iou > iou_thres and m[bi] not in detected:
                                                correct[i] = 1
                                                detected.append(m[bi])

                        # Append statistics (correct, conf, pcls, tcls)
                        stats.append((correct, pred[:, 4].cpu(), pred[:, 6].cpu(), tcls))

        # Compute statistics
        stats = [np.concatenate(x, 0) for x in list(zip(*stats))]  # to numpy
        if len(stats):
                p, r, ap, f1, ap_class = ap_per_class(*stats)
                mp, mr, mAP, mf1 = p.mean(), r.mean(), ap.mean(), f1.mean()
                nt = np.bincount(stats[3].astype(np.int64), minlength=nc)  # number of targets per class
        else:
                nt = torch.zeros(1)

        # Print results
        pf = '%20s' + '%10.3g' * 6  # print format
        print(pf % ('all', seen, nt.sum(), mp, mr, mAP, mf1))

        # Return results
        maps = np.zeros(nc) + mAP
        for i, c in enumerate(ap_class):
                maps[c] = ap[i]

        return (mp, mr, mAP, mf1, *(loss / len(dataloader)).tolist()), maps
reference_memristor = memtorch.bh.memristor.VTEAM
reference_memristor_params = {'time_series_resolution': 1e-10}
memristor = reference_memristor(**reference_memristor_params)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = Darknet(opt.cfg).to(device)
if opt.weights:
        if opt.weights.endswith(".pt"):
                model.load_state_dict(torch.load(opt.weights,map_location=device)['model'])
        else:
                _ = load_darknet_weights(model, opt.weights)

patched_model = patch_model(copy.deepcopy(model),
                          memristor_model=reference_memristor,
                          memristor_model_params=reference_memristor_params,
                          module_parameters_to_patch=[torch.nn.Linear,torch.nn.Conv2d],
                          mapping_routine=naive_map,
                          transistor=True,
                          programming_routine=None,
                          scheme=memtorch.bh.Scheme.DoubleColumn,
                          tile_shape=(128,128),
                          max_input_voltage=0.3,
                          scaling_routine=naive_scale,
                          ADC_resolution=4,
                          ADC_overflow_rate=0.,
                          quant_method='linear')
patched_model.tune_()
data = parse_data_cfg(opt.data)
nc = int(data['classes'])
test_path = data['valid']
dataset = LoadImagesAndLabels(test_path, opt.img_size, opt.batch_size)
dataloader = DataLoader(dataset,
                        batch_size=opt.batch_size,
                        num_workers=min([os.cpu_count(), opt.batch_size, 16]),
                        pin_memory=True,
                        collate_fn=dataset.collate_fn)
patched_model_ = apply_nonidealities(copy.deepcopy(patched_model),
                non_idealities=[memtorch.bh.nonideality.NonIdeality.DeviceFaults],
                lrs_proportion=0.25,
                hrs_proportion=0.10,
                electroform_proportion=0)
patched_model_.tune_()
with torch.no_grad():
        origin_model_metric = test(patched_model,dataloader)
print("mAP:",f'{origin_model_metric[1].mean():.6f}')
```
I can run the demo you provided normally with the accuracy degrade. However, in my own code , no matter what non-ideal factors I add, the accuracy of the patched_model doesn't change. This problem has been bothering me for days.  Hope you can give me some advice. 
Thank you very much!

**Comment by MySHworks** [comment]
Hello, I  have used the Memtorch library you released to simulate forward reasoning in networks with memristors, recently. I have to say it's a very handy library.  However, one problem I have found in my patched use is that if the network is built using torch.nn.Sequential container, patched does not seem to change the associated Conv2d layer. As a result, the precision of patched_model remains unchanged no matter how the relevant parameters of patched_model are adjusted.
For complex models, the code will becomes complex if you do not build it using torch.nn.Sequential container. So I am wondering if you have any other suggestions?
Thank you very much!

**Comment by coreylammie** [comment]
Hi @MySHworks,

Apologies for my late response! I have been focused on implementing support for comprehensive modeling of source and line resistance. I can confirm that your original issue was caused by using `torch.nn.Sequential` containers. 

It appears that the patching procedure defined in [memtorch.mn.Module.patch_model](https://github.com/coreylammie/MemTorch/blob/master/memtorch/mn/Module.py#L24-L157) is currently incompatible with `torch.nn.Sequential` containers. I have created a separate issue (#87) detailing this. Thankfully it should be a fairly easy fix- I will try attend to this later today, and will update this issue when #87 is closed and the functionality is merged to the master branch.

**Comment by coreylammie** [comment]
Hi @MySHworks,

This fix has been merged to master in #88. I have tested it using `torch.nn.Sequential` containers with and without explicitly named layers (using `OrderedDict`), and with and without `CUDA` support. 

> This functionality was verified using the following code snippet:
> 
> ```
> import torch
> from torch.autograd import Variable
> import memtorch
> import torch.nn as nn
> import torch.nn.functional as F
> import torch.optim as optim
> import numpy as np
> import copy
> from memtorch.mn.Module import patch_model
> from memtorch.map.Input import naive_scale
> from memtorch.map.Parameter import naive_map
> from memtorch.bh.nonideality.NonIdeality import apply_nonidealities
> from collections import OrderedDict
> 
> 
> class Net(nn.Module):
>     def __init__(self):
>         super(Net, self).__init__()
>         self.convs = nn.Sequential(nn.Conv2d(1, 20, 5, 1), nn.MaxPool2d(2, 2), nn.Conv2d(20, 50, 5, 1), nn.MaxPool2d(2, 2), nn.ReLU())
>         self.fc1 = nn.Sequential(OrderedDict([('fc1', nn.Linear(4*4*50, 500))]))
>         self.fc2 = nn.Linear(500, 10)
> 
>     def forward(self, x):
>         x = self.convs(x)
>         x = x.view(-1, 4*4*50)
>         x = F.relu(self.fc1(x))
>         x = self.fc2(x)
>         return x
> 
> device = torch.device('cpu' if 'cpu' in memtorch.__version__ else 'cuda')
> model = Net().to(device)
> reference_memristor = memtorch.bh.memristor.VTEAM
> reference_memristor_params = {'time_series_resolution': 1e-10}
> patched_model = patch_model(copy.deepcopy(model),
>                           memristor_model=reference_memristor,
>                           memristor_model_params=reference_memristor_params,
>                           module_parameters_to_patch=[torch.nn.Conv2d, torch.nn.Linear],
>                           mapping_routine=naive_map,
>                           transistor=True,
>                           programming_routine=None,
>                           tile_shape=(128, 128),
>                           max_input_voltage=0.3,
>                           scaling_routine=naive_scale,
>                           ADC_resolution=8,
>                           ADC_overflow_rate=0.,
>                           quant_method='linear')
> patched_model.tune_()
> patched_model_ = apply_nonidealities(copy.deepcopy(patched_model),
>                                   non_idealities=[memtorch.bh.nonideality.NonIdeality.DeviceFaults],
>                                   lrs_proportion=0.5,
>                                   hrs_proportion=0.5,
>                                   electroform_proportion=0)
> patched_model_.tune_()
> ```

Could you please confirm that this works for your specific use-case? Thanks again for raising the issue!

**Comment by MySHworks** [comment]
Thank you for providing such a simple solution to this problem. With your help, I have successfully solved the previous problem. Thank you again for your help.
However, I think the specific form of many networks is not the same, or to make some small modifications on this basis to be applicable. For example, in my model, each Convolution and LeakReLU module is placed in a torch.nn.Sequential container and then module_list, so if we convert according to the source code, we will lose the LeakyReLU module. I wonder if there's a better way to make it work for more different models.
Looking forward to your reply. 
Thank you very much!

**Comment by coreylammie** [comment]
Hi @MySHworks,

No problem at all! Looking at the most recent PyTorch documentation, it appears that both `torch.nn.ModuleList` and `torch.nn.ModuleDict` can be used to store sub-modules and `torch.nn.Sequential` containers. It is unclear to what extent these can be nested, but it should be possible to iterate through all contains to flatten/extract all layers sequentially. 

I have created a separate issue (#91) detailing this. I will update this thread once the issue has been fixed- my current intuition is to iterate through each element of each container and to check if any elements are containers recursively.

**Comment by MySHworks** [comment]
Hello, I looked at your quantization code before when I was debugging, but I didn't find the real quantization part memtorch_binding.quantize(). May I ask where the code of this part is? I have encountered some problems in model quantification recently, and I really want to learn it.
Thank you very much!

**Comment by coreylammie** [comment]
Hi @MySHworks,

Methods defined in [memtorch.bh.Quantize.py](https://github.com/coreylammie/MemTorch/blob/master/memtorch/bh/Quantize.py) and `memtorch_binding.quantize()` call C++ functions defined in  [https://github.com/coreylammie/MemTorch/blob/master/memtorch/cpp/quantize.cpp](https://github.com/coreylammie/MemTorch/blob/master/memtorch/cpp/quantize.cpp) using `pybind11` bindings.

Previous versions of MemTorch have used quantization routines from the [pytorch-playground](https://github.com/aaron-xichen/pytorch-playground), which should be functionally equivalent to the above C++ routines. `pytorch-playground` was previously integrated using a sub-module, and was called directly from [memtorch.bh.Quantize.py](https://github.com/coreylammie/MemTorch/blob/27b1880aeeb5cf112f1f327b77a21f85a19b1b03/memtorch/bh/Quantize.py) in [27b1880aee](https://github.com/coreylammie/MemTorch/tree/27b1880aeeb5cf112f1f327b77a21f85a19b1b03). 

If you would like, in the next release, I can add backwards compatibility, so that both C++/CUDA bindings and Python routines are accessible for `memtorch.bh.Quantize.py`. You are welcome to extend/modify this code as you see fit.

**Comment by MySHworks** [comment]
Hello, I would like to ask you some questions in the process of using memtorch.In the process of simulation of the finite conductivity state I found it didn't really quantify, the reason is that the "memtorch/bh/nonideality FiniteConductanceStates py" file try quantitative function of Max and min appeared error.Error: Expected Scalar type Float but found Double.
I don't know what forms of Max and min should be passed in correctly. 
In addition, the two models seem to be the same after the problems occurred in the simulation of the finite conductance state, but the results obtained after tune_() adjustment are completely different, the latter Tune shows a high score, but the accuracy is close to 0.If the latter is not tune_() adjusted, the accuracy is the same as the former.I am very confused about this question and looking forward to your reply.

**Comment by coreylammie** [comment]
Hi @MySHworks,

Apologies for the delayed response! I have looked into this further, and both issues should now be fixed in #110.

**Comment by 24367452** [comment]
Hello, I am still facing the problem of changing the finite conductivity state but maintaining the same accuracy. How can I correctly use quantization @coreylammie @MySHworks

**Comment by 24367452** [comment]
Hello, I am still facing the problem of changing the finite conductivity state without changing the accuracy. How can I correctly use quantization? Thank you for your answer @coreylammie @MySHworks

**Comment by 24367452** [comment]
Hi, I am still facing the problem of changing the state of finite conductance but accuracy remains the same, how do I use quantification correctly, thank you for your answer! @coreylammie @MySHworks
